### ISSUE TITLE
[SERVER] auth api 설계

### ISSUE THREAD

**Issue by dlwndms0812** [SWU-Running-Coach/Running_Coach_SERVER#1]
## 자세한 기능 설명
- swaggerhub 연동
- 임시 api 설계

## To-do

- [x] 회원가입 api 설계
- [x] 로그인 api 설계
- [x] 비밀번호 찾기 api 설계
- [x] access token 재발급 api 설계
- [x] SwaggerHub 연동
