### ISSUE TITLE
[SERVER] Response 클래스 생성

### ISSUE THREAD

**Issue by dlwndms0812** [SWU-Running-Coach/Running_Coach_SERVER#2]
## 자세한 기능 설명

- ResponseEntity를 통해 응답시 필요한 클래스 생성
- 상태코드 및 메시지 / 상태코드, 메시지 및 데이터를 담도록 2가지로 구현

## To-do

- [x] 상태 코드 클래스 생성
- [x] 상태 메세지 클래스 생성
- [x] 상태 코드, 메세지, 데이터를 담는 클래스 생성
- [x] 테스트
